#!/bin/bash

git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/ActionsNetlify.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/AppRun.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Automation.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/AwesomeTauri.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/BenchMarkElectron.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/BenchMarkResults.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/BinaryReleases.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/BoardVoter.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/CargoMobile2.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/CreatePullRequest.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/CreateTauriApp.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Deno.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/DNSAutomation.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/DocusaurusMeiliSearchIndexer.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Egui.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/FixPathENVRS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/GHTangleRelease.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/GipFS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/GirFiles.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/GlobalHotKey.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Glutin.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/GovernanceAndGuidance.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/JavaScriptCoreRS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LibAppIndicatorRS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LinuxDeployPluginGstreamer.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/LinuxDeployPluginGtk.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Meetings.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/MeiliSearchDocsearch.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/MSEdgeDriverManifestCache.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Muda.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/NSISTauriUtils.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/PluginsWorkspace.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Realworld.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/RFCs.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/RustDocusaurus.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/RustICNS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/RustXCodePlugin.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/SmokeTests.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Soup2RS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Tao.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Tauri.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriStudio.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriAction.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriBindgen.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriCon.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriDialogRS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriDiscordBot.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriDocs.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriEGUI.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriForage.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriGitHubBot.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriHotKeyRS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriIncludeDir.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriInliner.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriInlinerRS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriInvokeHTTP.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriLand.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginApp.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginAuthenticator.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginAutostart.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginCLI.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginClipboardManager.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginDialog.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginFS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginFSExtra.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginFSWatch.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginGlobalShortCut.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginHTTP.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginLocalhost.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginLog.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginNotification.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginOS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginPersistedScope.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginPositioner.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginProcess.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginShell.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginSingleInstance.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginSQL.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginStore.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginStrongHold.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginUpdater.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginUpload.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginWebSocket.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginWindow.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriPluginWindowState.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriSearch.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriTheia.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriToml.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TauriWebpack.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TrayIcon.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TypeDocPluginMarkdown.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/TypeDocusaurus.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/VueCLIPluginTauri.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/WebKit2GTKRS.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/WebView.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Win7Notifications.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/WindowShadows.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/WindowVibrancy.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Winit.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/WinRes.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/WinRTNotification.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/WorkflowTestBed.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/Wry.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/WryMobile.git
git submodule add --depth 1 ssh://git@github.com/CodeEditorLand/ZSergeWebview.git
